### ISSUE TITLE
Missing `SA_RESTART` in `sigaction`.

### ISSUE THREAD

**Issue by nouredd2** [rhit-csse332/csse332-labs#1]
`sigaction` does not set `SA_RESTART` by default, which causes it to behave differently than `signal`, causing bad behavior in simpleshell.

---

I had a student run into a cool bug with the simple shell assignment. What would you think of tweaking the starting sigaction examples to all set the sa_flag SA_RESTART?
 
It turns out that the sigaction code we give them is not a 1-1 replacement for signal because in glibc, [signal sets SA_RESTART](https://elixir.bootlin.com/glibc/latest/source/sysdeps/posix/signal.c#L44) when it calls sigaction. This is the documented behavior in signal(2). That surprised me.
 
In his simpleshell code, my student was manually catching SIGCHLD. He was getting divergent behavior whether he used the old signal vs sigaction to listen for a background command’s termination:
signal(): everything worked great!
sigaction: when the command finished, the last typed command tried to run again, but with one letter missing at the end.
 
Simpleshell was partially at fault here. We read from the command line as follows:
 
fgets(command, 82, stdin);
 
That precludes the possibility that fgets might fail. Turns out: SIGCHLD will cause fgets to fail. Old signal() will restart the failed read as if nothing went wrong. Our sigaction code will not and will cause fgets to return NULL. perror will report “Interrupted system call” if you care to listen, but we do not. So, our simple shell executes with the old buffer.
 
Setting SA_RESTART seems like what you would normally want to do. Should it be the default in all our examples?

**Comment by mahays0** [comment]
Fixed in 42c4b4f.
